CC = g++
CFLAGS = -I.

all: builder factory prototype

builder: builder.cpp
	$(CC) $(CFLAGS) builder.cpp -o builder

factory: factory.cpp
	$(CC) $(CFLAGS) factory.cpp -o factory

prototype: prototype.cpp
	$(CC) $(CFLAGS) prototype.cpp -o prototype
