CC = g++
CFLAGS = -I.

all: builder factory prototype singleton singleton2

builder: builder.cpp
	$(CC) $(CFLAGS) builder.cpp -o exe_builder

factory: factory.cpp
	$(CC) $(CFLAGS) factory.cpp -o exe_factory

prototype: prototype.cpp
	$(CC) $(CFLAGS) prototype.cpp -o exe_prototype

singleton: singleton.cpp
	$(CC) $(CFLAGS) singleton.cpp -o exe_singleton

singleton2: singleton2.cpp
	$(CC) $(CFLAGS) singleton2.cpp -o exe_singleton2
